<!DOCTYPE html>
<html lang="pt-BR">
<head><meta charset="utf-8"><title>{{ $dispatch->code() }}</title><style>
    @page{margin:38px 42px}*{box-sizing:border-box}body{margin:0;color:#142b45;font-family:DejaVu Sans,sans-serif;font-size:10px}.top{padding-bottom:14px;border-bottom:3px solid #cba62b}.brand{font-size:21px;font-weight:bold;color:#0b315d}.brand span{color:#b58b16}.code{float:right;text-align:right}.clear{clear:both}.kicker{margin-top:16px;color:#98730f;font-size:8px;font-weight:bold;text-transform:uppercase}h1{margin:5px 0 4px;font-size:20px}h2{margin:20px 0 7px;color:#0b315d;font-size:12px}.status{display:inline-block;padding:4px 7px;background:#e7f5ee;color:#126c4b;font-weight:bold}.grid{width:100%;border-collapse:collapse}.grid td{width:50%;padding:9px;border:1px solid #dce3e9;vertical-align:top}.grid small{display:block;color:#6c7887;font-size:7px;text-transform:uppercase}.grid strong{display:block;margin-top:3px}.timeline{width:100%;border-collapse:collapse}.timeline th{padding:7px;background:#0b315d;color:#fff;text-align:left;font-size:8px}.timeline td{padding:7px;border-bottom:1px solid #dce3e9;vertical-align:top}.hash{font-family:DejaVu Sans Mono,monospace;font-size:7px;word-break:break-all}.notice{margin-top:20px;padding:10px;border-left:3px solid #cba62b;background:#f8f6ee;color:#536173}.signatures{margin-top:48px;width:100%}.signatures td{width:50%;padding:0 24px;text-align:center}.line{padding-top:5px;border-top:1px solid #526174}footer{position:fixed;right:0;bottom:-20px;left:0;border-top:1px solid #dce3e9;padding-top:6px;color:#758293;font-size:7px}
</style></head>
<body>
    <div class="top"><div class="code"><strong>{{ $dispatch->code() }}</strong><br><span class="status">{{ $dispatch->statusLabel() }}</span></div><div class="brand">Trilha<span>Gov</span></div><div class="clear"></div><p class="kicker">Protocolo institucional municipal</p><h1>Recibo de remessa do relatório mensal</h1><p>{{ $dispatch->municipality->name }}/{{ $dispatch->municipality->state }} · {{ $report->code() }} · competência {{ $report->periodLabel() }}</p></div>
    <h2>Destinatário e protocolo</h2><table class="grid"><tr><td><small>Órgão destinatário</small><strong>{{ $dispatch->recipient_name }}</strong>{{ $dispatch->recipient_unit }}</td><td><small>Tipo / meio</small><strong>{{ $dispatch->recipientTypeLabel() }}</strong>{{ $dispatch->deliveryMethodLabel() }}</td></tr><tr><td><small>Documento oficial</small><strong>{{ $dispatch->official_document_number ?: 'Não protocolado' }}</strong></td><td><small>Protocolo</small><strong>{{ $dispatch->protocol_number ?: 'Não protocolado' }}</strong></td></tr><tr><td><small>Prazo municipal</small><strong>{{ $dispatch->due_at->format('d/m/Y') }}</strong>{{ $dispatch->legal_basis ?: 'Prazo operacional informado pelo Município' }}</td><td><small>Responsável interno</small><strong>{{ $dispatch->responsibleUser?->name ?? 'Gestores do Município' }}</strong></td></tr></table>
    <h2>Integridade do relatório remetido</h2><table class="grid"><tr><td><small>Relatório</small><strong>{{ $report->code() }}</strong>Emitido em {{ $report->issued_at->format('d/m/Y H:i') }} por {{ $report->issuer->name }}</td><td><small>SHA-256 da fotografia</small><span class="hash">{{ $report->snapshot_sha256 }}</span></td></tr></table>
    <h2>Linha do tempo documental</h2><table class="timeline"><thead><tr><th>Evento</th><th>Data</th><th>Responsável</th><th>Protocolo / evidência</th></tr></thead><tbody>@foreach($dispatch->events->sortBy('occurred_at') as $event)<tr><td><strong>{{ $event->label() }}</strong><br>{{ $event->message }}</td><td>{{ $event->occurred_at->format('d/m/Y H:i') }}</td><td>{{ $event->creator->name }}</td><td>{{ $event->protocol_number ?: '—' }}@if($event->evidence_sha256)<br><span class="hash">{{ $event->evidence_sha256 }}</span>@endif</td></tr>@endforeach</tbody></table>
    <div class="notice"><strong>Registro de apoio à governança municipal.</strong> Este recibo organiza a cadeia documental da remessa. O protocolo oficial e seus efeitos permanecem sujeitos ao sistema, à norma e ao procedimento adotados pelo Município e pelo órgão destinatário.</div>
    <table class="signatures"><tr><td><div class="line">Responsável pela remessa</div></td><td><div class="line">Recebimento do órgão destinatário</div></td></tr></table>
    <footer>Gerado pelo TrilhaGov em {{ now()->format('d/m/Y H:i') }} · referência {{ $dispatch->reference }}</footer>
</body></html>
