@extends('layouts.app')

@section('title', $dispatch->code().' | TrilhaGov')

@section('content')
    <div class="dispatch-heading mb-4">
        <div>
            <a class="back-link" href="{{ route('report-dispatches.index', $report) }}"><i data-lucide="arrow-left" aria-hidden="true"></i>Remessas de {{ $report->code() }}</a>
            <p class="page-kicker mt-3 mb-2">{{ $dispatch->recipientTypeLabel() }} · {{ $report->periodLabel() }}</p>
            <div class="d-flex flex-wrap align-items-center gap-2"><h1 class="h3 mb-0">{{ $dispatch->code() }}</h1><span class="dispatch-status status-{{ $dispatch->status }}">{{ $dispatch->statusLabel() }}</span></div>
            <p class="text-secondary mb-0 mt-2">{{ $dispatch->recipient_name }}@if($dispatch->recipient_unit) · {{ $dispatch->recipient_unit }}@endif</p>
        </div>
        <div class="dispatch-actions"><a class="btn btn-outline-primary" href="{{ route('governance-reports.pdf', $report) }}"><i data-lucide="file-text" aria-hidden="true"></i>Relatório</a><a class="btn btn-primary" href="{{ route('report-dispatches.receipt', $dispatch) }}"><i data-lucide="receipt-text" aria-hidden="true"></i>Recibo PDF</a></div>
    </div>

    <x-validation-summary />

    @if($dispatch->isOverdue())<div class="dispatch-warning mb-4"><i data-lucide="triangle-alert" aria-hidden="true"></i><div><strong>Prazo municipal vencido</strong><p>O envio deveria ter sido registrado até {{ $dispatch->due_at->format('d/m/Y') }}. O alerta permanece ativo até o protocolo.</p></div></div>@endif

    <div class="dispatch-overview mb-4">
        <section class="content-panel">
            <div class="content-panel-header dispatch-panel-header"><div><p class="page-kicker mb-1">Destinatário</p><h2 class="h5 mb-0">Dados institucionais</h2></div></div>
            <dl class="dispatch-facts"><div><dt>Órgão</dt><dd>{{ $dispatch->recipient_name }}</dd></div><div><dt>Unidade</dt><dd>{{ $dispatch->recipient_unit ?: 'Não informada' }}</dd></div><div><dt>Meio formal</dt><dd>{{ $dispatch->deliveryMethodLabel() }}</dd></div><div><dt>E-mail</dt><dd>{{ $dispatch->recipient_email ?: 'Não informado' }}</dd></div><div><dt>Prazo local</dt><dd>{{ $dispatch->due_at->format('d/m/Y') }}</dd></div><div><dt>Responsável</dt><dd>{{ $dispatch->responsibleUser?->name ?? 'Gestores do Município' }}</dd></div><div class="span-2"><dt>Base local</dt><dd>{{ $dispatch->legal_basis ?: 'Prazo operacional informado pelo Município' }}</dd></div></dl>
        </section>
        <section class="content-panel">
            <div class="content-panel-header dispatch-panel-header"><div><p class="page-kicker mb-1">Protocolo</p><h2 class="h5 mb-0">Identificação do envio</h2></div></div>
            <dl class="dispatch-facts single"><div><dt>Documento oficial</dt><dd>{{ $dispatch->official_document_number ?: 'Aguardando envio' }}</dd></div><div><dt>Protocolo</dt><dd>{{ $dispatch->protocol_number ?: 'Aguardando envio' }}</dd></div><div><dt>Enviado em</dt><dd>{{ $dispatch->sent_at?->format('d/m/Y H:i') ?? 'Não enviado' }}</dd></div><div><dt>Recebido / devolvido</dt><dd>{{ $dispatch->acknowledged_at?->format('d/m/Y H:i') ?? $dispatch->rejected_at?->format('d/m/Y H:i') ?? 'Sem retorno' }}</dd></div></dl>
        </section>
    </div>

    @if($canEdit && $dispatch->status === \App\Models\MunicipalReportDispatch::STATUS_PREPARED)
        <section class="content-panel mb-4">
            <div class="content-panel-header dispatch-panel-header"><div><p class="page-kicker mb-1">Etapa 1</p><h2 class="h5 mb-0">Registrar envio oficial</h2></div><span class="small text-secondary">Comprovante obrigatório · até 10 MB</span></div>
            <form class="dispatch-action-form" method="POST" action="{{ route('report-dispatches.send', $dispatch) }}" enctype="multipart/form-data">@csrf<input name="_submission_token" type="hidden" value="{{ $sendToken }}"><div><label class="form-label" for="official_document_number">Número do ofício ou documento <span class="required-mark">*</span></label><input class="form-control @error('official_document_number') is-invalid @enderror" id="official_document_number" name="official_document_number" value="{{ old('official_document_number') }}" maxlength="120" required>@error('official_document_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="protocol_number">Protocolo <span class="required-mark">*</span></label><input class="form-control @error('protocol_number') is-invalid @enderror" id="protocol_number" name="protocol_number" value="{{ old('protocol_number') }}" maxlength="160" required>@error('protocol_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="sent_at">Data e hora <span class="required-mark">*</span></label><input class="form-control @error('sent_at') is-invalid @enderror" id="sent_at" name="sent_at" type="datetime-local" value="{{ old('sent_at', now()->format('Y-m-d\TH:i')) }}" max="{{ now()->format('Y-m-d\TH:i') }}" required>@error('sent_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="evidence">Comprovante <span class="required-mark">*</span></label><input class="form-control @error('evidence') is-invalid @enderror" id="evidence" name="evidence" type="file" accept=".pdf,.txt,.csv,.jpg,.jpeg,.png,.eml,.msg" required>@error('evidence')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="span-3"><label class="form-label" for="message">Observação do envio</label><textarea class="form-control @error('message') is-invalid @enderror" id="message" name="message" rows="2" maxlength="3000">{{ old('message') }}</textarea>@error('message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><button class="btn btn-primary" type="submit"><i data-lucide="send" aria-hidden="true"></i>Registrar protocolo</button></form>
        </section>
    @endif

    @if($canEdit && $dispatch->status === \App\Models\MunicipalReportDispatch::STATUS_SENT)
        <section class="content-panel mb-4">
            <div class="content-panel-header dispatch-panel-header"><div><p class="page-kicker mb-1">Etapa 2</p><h2 class="h5 mb-0">Registrar retorno do destinatário</h2></div><span class="small text-secondary">Confirmação ou devolução documentada</span></div>
            <form class="dispatch-action-form" method="POST" action="{{ route('report-dispatches.return', $dispatch) }}" enctype="multipart/form-data">@csrf<input name="_submission_token" type="hidden" value="{{ $returnToken }}"><div><label class="form-label" for="result">Resultado <span class="required-mark">*</span></label><select class="form-select @error('result') is-invalid @enderror" id="result" name="result" required><option value="acknowledged" @selected(old('result') === 'acknowledged')>Recebimento confirmado</option><option value="rejected" @selected(old('result') === 'rejected')>Documento devolvido</option></select>@error('result')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="occurred_at">Data e hora <span class="required-mark">*</span></label><input class="form-control @error('occurred_at') is-invalid @enderror" id="occurred_at" name="occurred_at" type="datetime-local" value="{{ old('occurred_at', now()->format('Y-m-d\TH:i')) }}" min="{{ $dispatch->sent_at->format('Y-m-d\TH:i') }}" max="{{ now()->format('Y-m-d\TH:i') }}" required>@error('occurred_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="return_protocol_number">Protocolo do retorno</label><input class="form-control @error('protocol_number') is-invalid @enderror" id="return_protocol_number" name="protocol_number" value="{{ old('protocol_number', $dispatch->protocol_number) }}" maxlength="160">@error('protocol_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="return_evidence">Comprovante <span class="required-mark">*</span></label><input class="form-control @error('evidence') is-invalid @enderror" id="return_evidence" name="evidence" type="file" accept=".pdf,.txt,.csv,.jpg,.jpeg,.png,.eml,.msg" required>@error('evidence')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="span-3"><label class="form-label" for="return_message">Manifestação do destinatário</label><textarea class="form-control @error('message') is-invalid @enderror" id="return_message" name="message" rows="2" maxlength="5000">{{ old('message') }}</textarea>@error('message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><button class="btn btn-primary" type="submit"><i data-lucide="check-check" aria-hidden="true"></i>Registrar retorno</button></form>
        </section>
    @endif

    <section class="content-panel mb-4">
        <div class="content-panel-header dispatch-panel-header"><div class="d-flex align-items-center gap-2"><i data-lucide="history" aria-hidden="true"></i><h2 class="h5 mb-0">Linha do tempo documental</h2></div><span class="small text-secondary">Eventos imutáveis</span></div>
        <div class="dispatch-timeline">@foreach($dispatch->events as $event)<article><span class="dispatch-timeline-icon"><i data-lucide="{{ match($event->type) {'sent' => 'send', 'acknowledged' => 'badge-check', 'rejected' => 'circle-alert', 'cancelled' => 'circle-x', default => 'file-plus-2'} }}" aria-hidden="true"></i></span><div><div class="d-flex flex-wrap justify-content-between gap-2"><strong>{{ $event->label() }}</strong><time>{{ $event->occurred_at->format('d/m/Y H:i') }}</time></div><p>{{ $event->message }}</p><small>{{ $event->creator->name }}@if($event->protocol_number) · protocolo {{ $event->protocol_number }}@endif</small>@if($event->evidence_storage_path)<div class="dispatch-evidence"><a href="{{ route('report-dispatches.evidence', [$dispatch, $event]) }}"><i data-lucide="paperclip" aria-hidden="true"></i>{{ $event->evidence_original_name }}</a><code>SHA-256 {{ substr($event->evidence_sha256, 0, 16) }}…</code></div>@endif</div></article>@endforeach</div>
    </section>

    @if($dispatch->status === \App\Models\MunicipalReportDispatch::STATUS_REJECTED && $canEdit)<div class="dispatch-retry mb-4"><div><i data-lucide="refresh-cw" aria-hidden="true"></i><span><strong>Nova tentativa preservando o histórico</strong><small>A devolução permanece registrada e será vinculada ao próximo protocolo.</small></span></div><a class="btn btn-primary" href="{{ route('report-dispatches.index', ['report' => $report, 'retry_of' => $dispatch->id]) }}#nova-remessa"><i data-lucide="copy-plus" aria-hidden="true"></i>Preparar nova tentativa</a></div>@endif

    @if($canCancel)<details class="dispatch-cancel"><summary>Cancelar preparação</summary><form method="POST" action="{{ route('report-dispatches.cancel', $dispatch) }}">@csrf<input name="_submission_token" type="hidden" value="{{ $cancelToken }}"><div><label class="form-label" for="reason">Justificativa <span class="required-mark">*</span></label><textarea class="form-control @error('reason') is-invalid @enderror" id="reason" name="reason" rows="2" minlength="5" maxlength="2000" required>{{ old('reason') }}</textarea>@error('reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><button class="btn btn-outline-danger" type="submit"><i data-lucide="circle-x" aria-hidden="true"></i>Confirmar cancelamento</button></form></details>@endif
@endsection
