<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><title>{{ $document['reference'] }}</title><style>
    @page { margin: 24px 28px; } body { color:#11273f; font:10px DejaVu Sans,sans-serif; } h1,h2,p { margin:0; } h1 { font-size:20px; } h2 { margin:16px 0 7px; color:#8a6800; font-size:12px; text-transform:uppercase; } .header { border-bottom:3px solid #c9a227; padding-bottom:13px; } .brand { color:#072b50; font-size:17px; font-weight:bold; } .meta { float:right; text-align:right; } .meta strong,.meta span { display:block; } .intro { margin-top:14px; padding:10px; background:#f2f5f8; } .grid { width:100%; margin-top:10px; border-collapse:collapse; } .grid td { width:25%; padding:7px; border:1px solid #d7dde4; vertical-align:top; } .grid small { display:block; color:#667789; text-transform:uppercase; } .text { line-height:1.55; white-space:pre-line; } table.items { width:100%; border-collapse:collapse; } .items th { padding:6px; background:#082d51; color:white; text-align:left; } .items td { padding:6px; border-bottom:1px solid #d7dde4; vertical-align:top; } .items td:nth-child(1) { width:8%; } .items td:nth-child(2) { width:12%; } .items td:nth-child(3) { width:28%; } .items td:nth-child(4) { width:13%; } .items td:nth-child(5) { width:12%; } .items td:nth-child(6) { width:27%; } .seal { margin-top:17px; padding-top:10px; border-top:1px solid #aab5c0; } .hash { margin-top:5px; font:8px monospace; word-break:break-all; } .footer { position:fixed; right:0; bottom:-10px; left:0; color:#758291; font-size:8px; text-align:center; }
    </style></head><body>
    <header class="header"><div class="meta"><strong>{{ $document['reference'] }}</strong><span>{{ $plan->statusLabel() }}</span></div><div class="brand">TrilhaGov</div><h1>Plano Anual de Auditoria das Emendas Municipais</h1><p>{{ $document['municipality']['name'] }}/{{ $document['municipality']['state'] }} · exercício {{ $document['plan']['fiscal_year'] }}</p></header>
    <div class="intro"><strong>{{ $document['plan']['title'] }}</strong><p>Documento de planejamento do Controle Interno Municipal.</p></div>
    <table class="grid"><tr><td><small>Coordenação</small>{{ $document['plan']['coordination_unit'] }}</td><td><small>Período</small>{{ $document['plan']['planned_start_label'] }} a {{ $document['plan']['planned_end_label'] }}</td><td><small>Versão</small>{{ $document['plan']['version'] }}</td><td><small>Emissão</small>{{ $plan->issued_at?->format('d/m/Y H:i') ?? 'Minuta' }}</td></tr></table>
    <h2>Objetivo</h2><p class="text">{{ $document['plan']['objective'] }}</p><h2>Metodologia</h2><p class="text">{{ $document['plan']['methodology'] }}</p><h2>Critérios de risco e seleção</h2><p class="text">{{ $document['plan']['risk_criteria'] }}</p><h2>Base normativa</h2><p class="text">{{ $document['plan']['normative_basis'] }}</p>
    <h2>Agenda anual aprovada</h2>
    <table class="items"><thead><tr><th>Data</th><th>Emenda</th><th>Objeto</th><th>Fase</th><th>Responsável</th><th>Escopo aprovado</th></tr></thead><tbody>@forelse($document['items'] as $item)<tr><td>{{ $item['planned_at_label'] }}</td><td><strong>{{ $item['amendment']['reference'] }}</strong><br>{{ $item['priority_label'] }}</td><td>{{ $item['amendment']['object'] }}</td><td>{{ $item['phase_label'] }}<br>{{ $item['frequency_label'] }}</td><td>{{ $item['assigned_user']['name'] }}</td><td>{{ $item['scope_notes'] }}</td></tr>@empty<tr><td colspan="6">Nenhuma verificação incluída.</td></tr>@endforelse</tbody></table>
    @if($document['plan']['management_notes'])<h2>Observações gerenciais</h2><p class="text">{{ $document['plan']['management_notes'] }}</p>@endif
    <div class="seal"><strong>{{ $plan->issued_at ? 'Emitido por '.$plan->issuer?->name : 'Minuta preparada por '.$plan->creator->name }}</strong><p>Hash SHA-256 da fotografia documental preservada:</p><div class="hash">{{ $plan->snapshot_sha256 ?? 'Será calculado na emissão formal.' }}</div></div>
    <div class="footer">TrilhaGov · Plano Anual de Auditoria Municipal · gerado em {{ now()->format('d/m/Y H:i') }}</div>
</body></html>
