<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><style>@page{margin:32px}body{color:#172133;font-family:DejaVu Sans,sans-serif;font-size:9px}.header{border-bottom:3px solid #0a2f5a;margin-bottom:16px;padding-bottom:12px}.header h1{font-size:20px;margin:8px 0 4px}.header p{color:#5f6c80;margin:0}.meta{display:flex;justify-content:space-between}.brand{color:#0a2f5a;font-size:14px;font-weight:bold}.facts{border-collapse:collapse;margin-bottom:14px;width:100%}.facts td{border:1px solid #d4dce4;padding:7px;vertical-align:top}.facts strong{color:#0a2f5a;font-size:8px;text-transform:uppercase}h2{color:#0a2f5a;font-size:13px;margin:16px 0 7px}table.data{border-collapse:collapse;width:100%}.data th,.data td{border-bottom:1px solid #d4dce4;padding:6px;text-align:left}.data th{background:#edf3f6;color:#0a2f5a}.warning{border-left:3px solid #b98910;margin:8px 0;padding:6px 9px}.footer{border-top:1px solid #d4dce4;color:#667085;margin-top:18px;padding-top:8px}</style></head><body>
@php
    $money = function ($value) {
        return 'R$ '.number_format((float) $value, 2, ',', '.');
    };
@endphp
<header class="header"><div class="meta"><strong>{{ $contract->code() }}</strong><span>{{ $contract->statusLabel() }}</span></div><div class="brand">TrilhaGov</div><h1>Dossiê de Obra e Contrato Municipal</h1><p>{{ $contract->municipality->name }}/{{ $contract->municipality->state }} · {{ $contract->amendment->reference }}</p></header>
<table class="facts"><tr><td><strong>Processo</strong><br>{{ $contract->process_number }}</td><td><strong>Contrato</strong><br>{{ $contract->contract_number ?: 'Não formalizado' }}</td><td><strong>Contratada</strong><br>{{ $contract->supplier_name ?: 'Não definida' }}</td></tr><tr><td><strong>Valor original</strong><br>{{ $money($contract->original_amount) }}</td><td><strong>Valor atualizado</strong><br>{{ $money($contract->current_amount) }}</td><td><strong>Vigência</strong><br>{{ $contract->effective_start_at?->format('d/m/Y') ?: '-' }} a {{ $contract->effective_end_at?->format('d/m/Y') ?: '-' }}</td></tr><tr><td colspan="3"><strong>Objeto</strong><br>{{ $contract->object }}</td></tr><tr><td><strong>Gestor</strong><br>{{ $contract->manager?->name ?: 'Não definido' }}</td><td><strong>Fiscal</strong><br>{{ $contract->inspector?->name ?: 'Não definido' }}</td><td><strong>Responsável técnico</strong><br>{{ $contract->technical_responsible ?: '-' }} · {{ $contract->technical_registration ?: '-' }}</td></tr></table>
@if($diagnostic['blockers'] || $diagnostic['warnings'])<h2>Diagnóstico</h2>@foreach([...$diagnostic['blockers'], ...$diagnostic['warnings']] as $item)<div class="warning">{{ $item }}</div>@endforeach@endif
<h2>Medições</h2><table class="data"><thead><tr><th>Nº</th><th>Período</th><th>Valor</th><th>Físico</th><th>Situação</th></tr></thead><tbody>@forelse($contract->measurements as $measurement)<tr><td>{{ $measurement->sequence }}</td><td>{{ $measurement->period_start_at->format('d/m/Y') }} a {{ $measurement->period_end_at->format('d/m/Y') }}</td><td>{{ $money($measurement->amount) }}</td><td>{{ number_format((float) $measurement->cumulative_physical_percentage, 2, ',', '.') }}%</td><td>{{ $measurement->statusLabel() }}</td></tr>@empty<tr><td colspan="5">Nenhuma medição registrada.</td></tr>@endforelse</tbody></table>
<h2>Termos aditivos</h2><table class="data"><thead><tr><th>Nº</th><th>Tipo</th><th>Valor</th><th>Prazo</th><th>Situação</th></tr></thead><tbody>@forelse($contract->addenda as $addendum)<tr><td>{{ $addendum->sequence }}</td><td>{{ $addendum->typeLabel() }}</td><td>{{ $money($addendum->value_change) }}</td><td>{{ $addendum->days_change }} dia(s)</td><td>{{ $addendum->statusLabel() }}</td></tr>@empty<tr><td colspan="5">Nenhum termo aditivo registrado.</td></tr>@endforelse</tbody></table>
<div class="footer">Documento gerado em {{ now()->format('d/m/Y H:i') }}. Conferência de apoio baseada nos dados registrados no TrilhaGov.</div></body></html>
