<!DOCTYPE html>
<html lang="pt-BR">
<head><meta charset="utf-8"><title>{{ $document['reference'] }}</title><style>body{font-family:DejaVu Sans,sans-serif;color:#172133;font-size:10px}h1,h2,h3{color:#071f3d}h1{font-size:18px;margin:0}h2{font-size:13px;border-bottom:1px solid #ccd5df;padding-bottom:4px;margin-top:18px}h3{font-size:11px;margin-bottom:4px}.header{border-bottom:3px solid #0a2f5a;padding-bottom:12px}.meta{width:100%;border-collapse:collapse;margin:12px 0}.meta td{border:1px solid #dce3ec;padding:7px;vertical-align:top}.label{color:#647085;font-size:8px;text-transform:uppercase}.procedure,.finding{border:1px solid #dce3ec;padding:9px;margin:8px 0;page-break-inside:avoid}.tag{display:inline-block;border:1px solid #aeb9c4;padding:2px 5px;margin-right:5px;font-size:8px}.evidence{font-size:8px;color:#4c596d}.hash{word-break:break-all;background:#f1f4f7;padding:7px}.footer{margin-top:20px;border-top:1px solid #ccd5df;padding-top:8px;color:#647085}</style></head>
<body>
<div class="header"><h1>{{ $document['reference'] }} · Programa de Auditoria</h1><p>{{ $document['municipality']['name'] }}/{{ $document['municipality']['state'] }} · {{ $document['annual_plan']['reference'] }} · {{ $document['amendment']['reference'] }}</p></div>
<table class="meta"><tr><td><span class="label">Título</span><br>{{ $document['program']['title'] }}</td><td><span class="label">Auditor líder</span><br>{{ $document['program']['lead_auditor']['name'] }}</td><td><span class="label">Supervisor</span><br>{{ $document['program']['supervisor']['name'] }}</td></tr><tr><td><span class="label">Amostragem</span><br>{{ $document['program']['sampling_method'] }} · {{ $document['program']['sample_size'] }}/{{ $document['program']['population_size'] }}</td><td><span class="label">Período</span><br>{{ $document['program']['start_at'] }} a {{ $document['program']['due_at'] }}</td><td><span class="label">Processo</span><br>{{ $document['amendment']['administrative_process'] ?? 'Não informado' }}</td></tr></table>
<h2>Objetivo e escopo</h2><p><strong>Objetivo:</strong> {{ $document['program']['objective'] }}</p><p><strong>Escopo:</strong> {{ $document['program']['scope'] }}</p><p><strong>População:</strong> {{ $document['program']['population_description'] }}</p><p><strong>Materialidade:</strong> {{ $document['program']['materiality_criteria'] }}</p>
<h2>Procedimentos e papéis de trabalho</h2>
@foreach($document['procedures'] as $procedure)<div class="procedure"><h3>P{{ str_pad($procedure['sequence'], 2, '0', STR_PAD_LEFT) }} · {{ $procedure['title'] }}</h3><span class="tag">{{ $procedure['status'] }}</span><p><strong>Objetivo:</strong> {{ $procedure['objective'] }}</p><p><strong>Método:</strong> {{ $procedure['test_method'] }}</p><p><strong>Amostra:</strong> {{ $procedure['sample_description'] }}</p><p><strong>Resultado:</strong> {{ $procedure['result'] ?? 'Pendente' }}</p>@foreach($procedure['evidences'] as $evidence)<p class="evidence">Evidência: {{ $evidence['original_name'] }} · SHA-256 {{ $evidence['sha256'] }}</p>@endforeach</div>@endforeach
<h2>Achados e recomendações</h2>
@forelse($document['findings'] as $finding)<div class="finding"><h3>{{ $finding['title'] }}</h3><span class="tag">{{ $finding['severity'] }}</span><p><strong>Critério:</strong> {{ $finding['criteria'] }}</p><p><strong>Condição:</strong> {{ $finding['condition'] }}</p>@if($finding['cause'])<p><strong>Causa:</strong> {{ $finding['cause'] }}</p>@endif @if($finding['effect'])<p><strong>Efeito:</strong> {{ $finding['effect'] }}</p>@endif<p><strong>Recomendação:</strong> {{ $finding['recommendation'] }}</p></div>@empty<p>Nenhum achado registrado.</p>@endforelse
<h2>Revisão e conclusão</h2><p><strong>Nota do supervisor:</strong> {{ $document['program']['supervisor_notes'] ?? 'Pendente' }}</p><p><strong>Conclusão:</strong> {{ $document['program']['conclusion'] ?? 'Pendente' }}</p>
@if($program->snapshot_sha256)<p class="hash"><strong>SHA-256:</strong> {{ $program->snapshot_sha256 }}</p>@endif
<div class="footer">Gerado em {{ now()->format('d/m/Y H:i') }} · TrilhaGov · Documento de controle municipal</div>
</body></html>
